### ISSUE TITLE
Issues with trying out example template

### ISSUE THREAD

**Issue by SirSpidey** [shawnbot/swagger-static#6]
I'm having trouble running the examples with stag. 
I think I installed stag via npm without problems. 
Then I tried to use the example template.html to try out the package. I assume that is possible.

I get the following output:

```
$ stag http://petstore.swagger.wordnik.com/api/api-docs/ template.html
reading and enhancing JSON from: http://petstore.swagger.wordnik.com/api/api-docs/

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/stag/node_modules/swagger-enhance/index.js:38:21)
    at Request.self.callback (/usr/local/lib/node_modules/stag/node_modules/request/request.js:368:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/stag/node_modules/request/request.js:1219:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/stag/node_modules/request/request.js:1167:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
$
```

Am I missing something obvious? Does this output make sense to you? Suggestions?

Thanks

**Comment by adamjerickson** [comment]
I get the same problem.  Any help?

**Comment by gfrivolt** [comment]
the same here, resource http://petstore.swagger.wordnik.com/api/api-docs/ does not seem to respond, I tried a different one `stag http://petstore.swagger.io/v2/swagger.json template.html` it fails with the following:

```
reading and enhancing JSON from: http://petstore.swagger.io/v2/swagger.json
/usr/local/lib/node_modules/stag/node_modules/async/lib/async.js:51
        if (arr.map) {
               ^
TypeError: Cannot read property 'map' of undefined
    at _map (/usr/local/lib/node_modules/stag/node_modules/async/lib/async.js:51:16)
    at _asyncMap (/usr/local/lib/node_modules/stag/node_modules/async/lib/async.js:234:15)
    at Object.map (/usr/local/lib/node_modules/stag/node_modules/async/lib/async.js:216:23
)
    at enhance (/usr/local/lib/node_modules/stag/node_modules/swagger-enhance/index.js:15:
9)
```
